kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: techmart
nodes:
  - role: control-plane
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
    extraPortMappings:
      # HTTP — access the store at http://localhost
      - containerPort: 80
        hostPort: 80
        protocol: TCP
      # HTTPS (optional)
      - containerPort: 443
        hostPort: 443
        protocol: TCP
  - role: worker
  - role: worker
